---
blueprint:
  name: Zigbee2MQTT - IKEA TRADFRI - 5 Button Remote - Custom Actions
  description: >-
    Use an IKEA TRADFRI 5-button remote via Zigbee2MQTT. Triggers on the device's
    zigbee2mqtt/<device>/action topic and maps action payloads (toggle, *_click, *_hold, etc.)
    to configurable Home Assistant actions.
  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control (optional)
      description: >-
        Optional: only for documenting/selecting the device in the UI.
        The automation trigger uses the MQTT topic you set below.
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI remote control
            - integration: mqtt
              manufacturer: IKEA of Sweden
              model: TRADFRI remote control

    mqtt_action_topic:
      name: Zigbee2MQTT action topic
      description: >-
        The MQTT topic that publishes the action payload, e.g.
        zigbee2mqtt/0x5c0272fffeac409d/action  (or zigbee2mqtt/<friendly_name>/action)
      selector:
        text:

    power_short:
      name: Short Press - Power Button (toggle)
      selector:
        action:
      default: []

    power_long:
      name: Long Press - Power Button (toggle_hold)
      selector:
        action:
      default: []

    dimup_short:
      name: Short Press - Dim Up (brightness_up_click)
      selector:
        action:
      default: []

    dimup_long:
      name: Long Press - Dim Up (brightness_up_hold)
      selector:
        action:
      default: []

    dimdown_short:
      name: Short Press - Dim Down (brightness_down_click)
      selector:
        action:
      default: []

    dimdown_long:
      name: Long Press - Dim Down (brightness_down_hold)
      selector:
        action:
      default: []

    colorup_short:
      name: Short Press - Color Up (arrow_right_click)
      selector:
        action:
      default: []

    colorup_long:
      name: Long Press - Color Up (arrow_right_hold)
      selector:
        action:
      default: []

    colordown_short:
      name: Short Press - Color Down (arrow_left_click)
      selector:
        action:
      default: []

    colordown_long:
      name: Long Press - Color Down (arrow_left_hold)
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_action_topic

variables:
  action_payload: "{{ trigger.payload }}"

action:
  - choose:
      # --- Power ---
      # Short press power button
      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'toggle' }}"
        sequence: !input power_short

      # Long press power button
      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'toggle_hold' }}"
        sequence: !input power_long

      # --- Brightness up ---
      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'brightness_up_click' }}"
        sequence: !input dimup_short

      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'brightness_up_hold' }}"
        sequence: !input dimup_long

      # --- Brightness down ---
      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'brightness_down_click' }}"
        sequence: !input dimdown_short

      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'brightness_down_hold' }}"
        sequence: !input dimdown_long

      # --- Arrow right / "color up" ---
      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'arrow_right_click' }}"
        sequence: !input colorup_short

      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'arrow_right_hold' }}"
        sequence: !input colorup_long

      # --- Arrow left / "color down" ---
      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'arrow_left_click' }}"
        sequence: !input colordown_short

      - conditions:
          - condition: template
            value_template: "{{ action_payload == 'arrow_left_hold' }}"
        sequence: !input colordown_long

    # Any other event (including *_release) does nothing, but will still restart/cancel loops due to mode: restart.
    default: []
